version: "3.8"
services:
  janus:
    image: vaibhz/janus-gateway-docker:0.10.3
    container_name: janus-gateway
    ports:
      - "8188:8188"
      - "8088:8088"
    volumes:
      - ./config:/usr/local/etc/janus
