name: Janus WebRTC Gateway Build and Push

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: tdemin/find-latest-tag@v1
        id: find-latest-tag
        with:
          repo: https://github.com/meetecho/janus-gateway.git
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: JANUS_LATEST_TAG=${{ steps.find-latest-tag.outputs.tag }}
          push: true
          tags: vaibhz/janus-webrtc-gateway:${{ steps.find-latest-tag.outputs.tag }}
